insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Endorsed to Acquire');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer/SMS Sent');
insert into statuses (status) values ('Endorsed to Acquire');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Not interested in Acquire/for demand science pooling');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Endorsed to Acquire');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Candidate not available');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('CNI');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('endorsed to IBEX Davao');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Already Applied In UHG');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNI');
insert into statuses (status) values ('For Pooling');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Forwarded to Accenture for validation');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Endorsed to IBEX Hanston');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNI');
insert into statuses (status) values ('Endorsed to TP - Pasay');
insert into statuses (status) values ('For CB');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('CNI');
insert into statuses (status) values ('Encoded to in Taleo');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer/for CB');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to IBEX Davao');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Currently enrolled / Interested in in Part-time jobs only');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to IBEX PQ');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('For CB on Monday');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('NI');
insert into statuses (status) values ('NI');
insert into statuses (status) values ('Endorsed to TP - Alphaland');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to Cebu IT Park');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('For email invite, TP-EDSA');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP-Cebu IT Park');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('No answer');

insert into statuses (status) values ('Endorsed to IBEX PQ');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to Ibex tomorrow');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to IBEX Davao');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not willing to relocate');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Didn''t meet salary expectation');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('For CB tomorrow morning');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('NI');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Endorsed to TP-IT Park');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('For CB tomorrow morning');
insert into statuses (status) values ('Endorsed to Cebu IT Park');
insert into statuses (status) values ('Failed TP/Undergrad');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('NI');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('For Accenture Validation');
insert into statuses (status) values ('Failed TP Cebu');
insert into statuses (status) values ('For Accenture Validation');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Sms sent for accenture interview');
insert into statuses (status) values ('CNR / for callback');
insert into statuses (status) values ('endorsed to TP Sucat 08-oct-2015');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Invited for interview and coaching session tomorrow 9:00AM');
insert into statuses (status) values ('Requested for Callback');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Edsa');
insert into statuses (status) values ('endorsed to tp It park');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('NO Answer / For callback');
insert into statuses (status) values ('Failed screening');
insert into statuses (status) values ('Endorsed to TP-Pasay');
insert into statuses (status) values ('Lookinf for part time only');
insert into statuses (status) values ('For accenture validation');
insert into statuses (status) values ('For accenture validation');
insert into statuses (status) values ('Failed screening');
insert into statuses (status) values ('Failed screening');
insert into statuses (status) values ('Failed screening');
insert into statuses (status) values ('Number unavailable');
insert into statuses (status) values ('Failed screening');
insert into statuses (status) values ('For CB 4pm');
insert into statuses (status) values ('Valid for accenture');
insert into statuses (status) values ('failed');

insert into statuses (status) values ('CNR');
insert into statuses (status) values ('For Accenture Validation');
insert into statuses (status) values ('For Pooling');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Encoded in Taleo  - Sept 7');
insert into statuses (status) values ('CNI');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Not Valid');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Encoded in Taleo  - Sept 12');
insert into statuses (status) values ('Endorsed to IBEX PQ - October 8');
insert into statuses (status) values ('NQ');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Not Valid');
insert into statuses (status) values ('Endorsed to IBEX Davao - October 13');
insert into statuses (status) values ('NQ');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNI');
insert into statuses (status) values ('Failed Screening');

insert into statuses (status) values ('Valid for Accenture');
insert into statuses (status) values ('Valid for Accenture');

insert into statuses (status) values ('NQ');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('endorsed to IBEX Davao');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Invited for on site coaching');
insert into statuses (status) values ('Endorsed to  DavaoTP / NI');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('for reprofiling/ for cv');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('For accenture validation');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Invited for coaching / for endorsement to tp-edsa');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNR');

insert into statuses (status) values ('Invited for on-site coaching');
insert into statuses (status) values ('No ANswer o both numbers / SMS sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Request Call back after 1 hr');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('Endorsed to TP-Cebu');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Validated by Accenture - For Toolkit');
insert into statuses (status) values ('Already sourced by another vendor');
insert into statuses (status) values ('On-hold (No demand) - Accenture');
insert into statuses (status) values ('Already sourced by another vendor');
insert into statuses (status) values ('Valid for Accenture');
insert into statuses (status) values ('Already sourced by another vendor');
insert into statuses (status) values ('Validated by Accenture - For Toolkit');
insert into statuses (status) values ('Valid for Accenture');
insert into statuses (status) values ('Accenture - Valid');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Not Available');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Requested Callback');
insert into statuses (status) values ('Poor Connection');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to IBEX Davao');
insert into statuses (status) values ('Endorsed to Acquire tommorow');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Accenture - For Validation');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Endorsed to TP CEbu IT Park tom');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Already scheduled for interview');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('Endorsed to IBEX davao - CSR');
insert into statuses (status) values ('For accenture validation');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Requested Callback 3pm');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer/SMS sent');
insert into statuses (status) values ('Already processed application at TP / Will reprofile to Ibex');
insert into statuses (status) values ('Not Available');
insert into statuses (status) values ('Endorsed to TP - Cebu IT Park CSR tomorrow');
insert into statuses (status) values ('Endorsed to TP - Cebu IT Park tomorrow');
insert into statuses (status) values ('Endorsed to TP Pasay tomorrow 10AM');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('Endorsed to TP-Pasay CSR / tomorrow 10AM');
insert into statuses (status) values ('Endorsed to EXL');
insert into statuses (status) values ('Accenture - Invalid');
insert into statuses (status) values ('Accenture - Valid');
insert into statuses (status) values ('BPOI - Paper Screening');
insert into statuses (status) values ('Accenture - Invalid');
insert into statuses (status) values ('Valid for Accenture');
insert into statuses (status) values ('Already sourced by another vendor');
insert into statuses (status) values ('Valid for Accenture');
insert into statuses (status) values ('Paperscreening - BPOI');
insert into statuses (status) values ('Paperscreening - BPOI');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer/SMS sent');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer for Callback');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer /  for Accenture validation ');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Candidate not available for Callback');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Failed');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Tp Exam / for accenture validation');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Invited for coaching session');
insert into statuses (status) values ('Was already endorsed to Ibex');
insert into statuses (status) values ('For accenture validation');
insert into statuses (status) values ('Endorsed to Acquire shaw on Monday 9:00 AM');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Endorsed to TP Edsa ');
insert into statuses (status) values ('No answer / SMS sent');
insert into statuses (status) values ('No answer / SMS sent');
insert into statuses (status) values ('Valid - Provide toolkit');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('endorsed to TP - Cebu it park 17-Oct-2015 ');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Candidate not available ');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Invited for Coaching /Sitel ');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Poor Connection / For Callback');
insert into statuses (status) values ('For validation CSR / ACCENTURE');
insert into statuses (status) values ('Already sourced by another vendor');
insert into statuses (status) values ('Endorsed to IGT');
insert into statuses (status) values ('Valid - Accenture');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park tomorrow 10AM CSR Pilot Class');
insert into statuses (status) values ('Endorsed to TP Baguio');
insert into statuses (status) values ('Called 2x/No asnwer ');
insert into statuses (status) values ('For callback on Monday 10-12 AM');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Endorsed to TP Sucat');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('For Callback on Monday');
insert into statuses (status) values ('N0 answer');
insert into statuses (status) values ('For callback');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Endorsed to TP-Cebu IT Park / CSR');
insert into statuses (status) values ('No answer /sms sent');
insert into statuses (status) values ('No answer /sms sent');
insert into statuses (status) values ('For accenture validation');
insert into statuses (status) values ('No answer /sms sent');
insert into statuses (status) values ('was already scheduled for tomorrow by a different vendor.');
insert into statuses (status) values ('CNR for CB');
insert into statuses (status) values ('Valid - Accenture');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No anwer SMS sent');
insert into statuses (status) values ('Endorsed to TP - IT Park / CSR - TRAVEL');
insert into statuses (status) values ('No answer sms sent');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer sms sent');
insert into statuses (status) values ('For accenture validation');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No answer sms sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Davao');
insert into statuses (status) values ('No answer sms sent');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('NI');
insert into statuses (status) values ('Endorsed to TP Cebu');
insert into statuses (status) values ('No answer/ sms sent');
insert into statuses (status) values ('No answer/ sms sent');
insert into statuses (status) values ('No answer/ sms sent');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('For endorsement to IGT will wait for date confirmation from the candidate');
insert into statuses (status) values ('Endorsed to WCC - IGT 22-OCT-2015 CSR-Travel');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP-IT Park tomorrow 10AM');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Endorsed to TP-Aura tomorrow');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Davao');
insert into statuses (status) values ('No answer sms sent');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Endorsed to TP-Cebu IT Park friday 10AM / CSR');
insert into statuses (status) values ('No answer sms sent');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Already sourced by another vendor');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Accenture - Valid');
insert into statuses (status) values ('Accenture - Provide Toolkit');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Poor reception / SMS sent for callback');
insert into statuses (status) values ('Endorsed to IGT- WCC 24-Oct-2015 10AM');

insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Already sourced by another vendor');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No  Answer/ For Callback');
insert into statuses (status) values ('No Answer / for callback');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('NI');
insert into statuses (status) values ('NI / receptionist job');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to IBEX global Davao 26-Oct-2015');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Accenture - Provide toolkit');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park Monday');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to PC');
insert into statuses (status) values ('BPOI - PaperScreening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No answer / SMS sent');
insert into statuses (status) values ('For endorsement to ACQUIRE');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Endorsed to TP - IT Park 10AM 27-Oct');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Sucat - Oct 26 10AM CSR');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park Oct. 26 10 AM');

insert into statuses (status) values ('Endorsed to IGT tomorrow 10AM');
insert into statuses (status) values ('Requested for Callback');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park Nov. 4 10 AM CSR');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer / sms sent');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Bacolod Oct-29-15 10AM CSR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Endorsed to IGT WCC November 9- 15 10AM CSR-Travel');
insert into statuses (status) values ('No Answer / sms sent');
insert into statuses (status) values ('Endorsed to TP EDSA Nov.2,15 CSR Dayshift');
insert into statuses (status) values ('Endorsed to Acquire Shaw November 3 10AM');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Endorsed to TP-Cebu IT park tomorrow 10AM');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP-Cebu IT park tomorrow 10AM');
insert into statuses (status) values ('Endorsed to tp baguio tomorrow 10AM');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer/SMS sent');
insert into statuses (status) values ('For CB 5PM');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Accenture - Invalid');
insert into statuses (status) values ('Accenture - Valid');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park Oct. 29 10AM');
insert into statuses (status) values ('Endorsed to TP - Baguio tomorrow 10AM');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Baguio Tomorrow 10 AM CSR');
insert into statuses (status) values ('No Answer / sms sent');
insert into statuses (status) values ('No Answer / sms sent');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park Nov.2 10AM CSR');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park Nov. 4 10AM CSR');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park Oct.28 1PM CSR');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('CNR/SMS sent');
insert into statuses (status) values ('No Answer/ SMS sent');
insert into statuses (status) values ('No Answer/ SMS sent');
insert into statuses (status) values ('Already hired by TP last month but was not able to comply with the requirements');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer/ SMS sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('For Accenture Validation');
insert into statuses (status) values ('No Answer/ SMS sent');
insert into statuses (status) values ('For OJT Application');
insert into statuses (status) values ('No Answer/ SMS sent');
insert into statuses (status) values ('No Answer/ SMS sent');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer/ SMS sent');
insert into statuses (status) values ('Endorsed to it park tp - 02-Nov 10AM CSR-Banking');
insert into statuses (status) values ('Endorsed to IGT WCC / Tomorrow 10AM');
insert into statuses (status) values ('Poor connection / For callback');
insert into statuses (status) values ('No Answer/ SMS sent');
insert into statuses (status) values ('Endorsed to TP Davao Oct.30 10AM');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to PC');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('Accenture - Valid');
insert into statuses (status) values ('CNR /For Callback');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('ENdorsed to TP Davao tomorrow 10AM CSR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park tomorrow 10AM CSR - Banking');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('Endorsed to TP Fairview November 2, 2015 10 AM CSR');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Endorsed to TP EDSA Greenfield tomorrow 1PM CSR');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to IGT McKinley Nov.4, 15 10AM');
insert into statuses (status) values ('Endorsed to it park tp - 02-Nov 10AM CSR-Banking');
insert into statuses (status) values ('Accenture - For Validation');
insert into statuses (status) values ('Accenture - Reallocate / Re-endorse');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No answer / sms sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park Nov 4, 2015 10AM CSR - Bankin');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('No answer / sms sent');
insert into statuses (status) values ('Endorsed to TP Fairview November 3,, 2015 10AM CSR');
insert into statuses (status) values ('No answer / sms sent');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('Failed');
insert into statuses (status) values ('KSI - For Validation');
insert into statuses (status) values ('Accenture - For Validation');
insert into statuses (status) values ('Accenture - For Validation');
insert into statuses (status) values ('Will be available next year');
insert into statuses (status) values ('EXL - For Validation');
insert into statuses (status) values ('PC Paper Screening');
insert into statuses (status) values ('Accenture - For Validation');
insert into statuses (status) values ('Accenture - For Validation');
insert into statuses (status) values ('Accenture - For Validation');
insert into statuses (status) values ('Accenture - For Validation');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('Valid - Provide toolkit');
insert into statuses (status) values ('Valid - Provide toolkit');
insert into statuses (status) values ('Accenture - For Validation');
insert into statuses (status) values ('Endorsed to TP');
insert into statuses (status) values ('Endorsed to IBEX PQ');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('For Validation for NNIT');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Validation for Accenture');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Invalid');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('No Contact');

insert into statuses (status) values ('No Contact');

insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Show-up Nov.9');
insert into statuses (status) values ('For Pooling');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('Encoded to Taleo');

insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to KSI');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Waiting for the result of Validation');
insert into statuses (status) values ('Waiting for the result of Validation');
insert into statuses (status) values ('For Paper Screening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Pooling');
insert into statuses (status) values ('Endorsed to CSS Corp');
insert into statuses (status) values ('For Callback by 5:30 PM');
insert into statuses (status) values ('Waiting for the result of Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Endorsed to TP Edsa');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Waiting for the result of Validation');
insert into statuses (status) values ('Over age, expected salary is 50K');
insert into statuses (status) values ('Invalid already sourced by other vendor');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Validation');

insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Screening Interview');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Invalid already sourced ');
insert into statuses (status) values ('Waiting for the result of validation');
insert into statuses (status) values ('Waiting for the result of validation');
insert into statuses (status) values ('Endorsed to client / TP Rockwell');
insert into statuses (status) values ('Endorsed to client');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('Endorsed to IGT');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Pooling');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('No Valid Phil No.');
insert into statuses (status) values ('CB');
insert into statuses (status) values ('CB');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('already Endorsed to Accenture');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Proximity issue');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Not Interested');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Endorsed to PC');
insert into statuses (status) values ('expected salary is 80K');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('CNI');
insert into statuses (status) values ('Wrong num / email sent');
insert into statuses (status) values ('No answer, For CB');
insert into statuses (status) values ('Invalid for NNIT');
insert into statuses (status) values ('Endorsed to TP Edsa');
insert into statuses (status) values ('For Reprofiling');
insert into statuses (status) values ('Endorsed to IGT WCC');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Endorsed to TP Edsa');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Cebu ');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Phone Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Edsa');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP MOA');
insert into statuses (status) values ('No contact number provide');
insert into statuses (status) values ('Endorsed to TP Baguio');
insert into statuses (status) values ('Endorsed to TP IT Park Cebu');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('For Accenture Validation');
insert into statuses (status) values ('Endorsed to TP MOA');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed TO Cebu IT Park');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP PQ');
insert into statuses (status) values ('For callback/ for accenture validation');
insert into statuses (status) values ('Candidate is not interested');
insert into statuses (status) values ('Endorsed to TP Rockwell Ortigas for TSR IT Helpdesk');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Wrong Number');
insert into statuses (status) values ('For callback ');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Phone Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Not Interested');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Endorsed to IBEX');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Invalid / With existing record in UHG');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('No Valid Phil No.');
insert into statuses (status) values ('Endorsed/Validation to Accenture');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Valid - For F2F interview 11/24/2015');
insert into statuses (status) values ('Endorsed to Accenture/Sent toolkit');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP - EDSA');
insert into statuses (status) values ('Former TP Employee');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('Wrong Number');
insert into statuses (status) values ('Endorsed to TP - Pasay');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Endorsed to IBEX');
insert into statuses (status) values ('Endorsed to IBEX PQ');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Fairview');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');

insert into statuses (status) values ('Endorsed to TP Fairview');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('No Answer/SMS Sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Waiting for Validation result from TP');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('Waiting for Validation result from Accenture');
insert into statuses (status) values ('Waiting for Validation result from TP');
insert into statuses (status) values ('Endorsed to Acquire');
insert into statuses (status) values ('For Pooling');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer/SMS Sent');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('For callback, not available for phone interview');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Encoded to taleo');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('Endorsed to Acquire Shaw');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to Acquire Shaw');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorse to Accenture for validation ');
insert into statuses (status) values ('No Answer / SMS sent');

insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Valid to Accenture');
insert into statuses (status) values ('Endorsed to TP ALPHALAND');
insert into statuses (status) values ('Failed');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Ringing No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('For Callback Tomorrow');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed To IBEX Tiendesitas');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('Not Interested');
insert into statuses (status) values ('Endorsed to UHG');
insert into statuses (status) values ('Interested in Part time only');
insert into statuses (status) values ('Endorsed to TP Cebu');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Endorsed to TP Cebu');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Failed');
insert into statuses (status) values ('Endorsed to TP Cebu');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('For Validation/sent to accenture');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For NNIT Project Manager');
insert into statuses (status) values ('For NNIT Senior IT Project Manager');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For CGI Validation for M3 Consultant');
insert into statuses (status) values ('For CGI Validation');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('Unreachable');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('Endorsed to IBEX Silver City');
insert into statuses (status) values ('Endorsed to TP Pasay');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Employed not Interested');
insert into statuses (status) values ('Endorsed to IBEX Davao');
insert into statuses (status) values ('For Pooling');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Failed');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('Endorsed to TP Rockwell Ortigas');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Already Employed');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed To ACQUIRE EASTWOOD');
insert into statuses (status) values ('Endorsed to TP CEBU IT PARK');
insert into statuses (status) values ('Endorsed To ACQUIRE EASTWOOD');
insert into statuses (status) values ('Endorsed to TP CEBU IT PARK');
insert into statuses (status) values ('Endorsed to TP CEBU IT PARK');
insert into statuses (status) values ('Endorsed to TP CEBU IT PARK');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('Will relocate to Cebu by January');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('Endorsed to TP MOA');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Cannot be reached');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('Endorsed to CEBU IT PARK');
insert into statuses (status) values ('Failed Phone Screening');
insert into statuses (status) values ('Encoded to taleo');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Encoded to taleo');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Endorsed to CEBU IT PARK');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Endorsed to CEBU IT PARK');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to CEBU IT PARK');
insert into statuses (status) values ('Endorsed to TP McKinley');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation TP');
insert into statuses (status) values ('For Validation TP/Accenture');
insert into statuses (status) values ('For Validation Accenture ');
insert into statuses (status) values ('For Validation Accenture ');
insert into statuses (status) values ('Endorsed to TP Paranaque');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Not Interested');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to TP EDSA');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Employed');
insert into statuses (status) values ('No Contact');


insert into statuses (status) values ('Endorsed to IBEX Davao');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For F2f interview');
insert into statuses (status) values ('For F2f interview');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Baguio');
insert into statuses (status) values ('Endorsed to CSS Corp');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('Endorsed to CSS Corp Taguig');
insert into statuses (status) values ('Endorsed to Cebu IT Park');
insert into statuses (status) values ('Already Employed');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to Cebu IT Park');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to TP Baguio');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Paranaque');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Valid to Accenture ');
insert into statuses (status) values ('F2F Interview ');
insert into statuses (status) values ('Already Applied to TP');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Candidate already on database of UHG');
insert into statuses (status) values ('Endorsed to IBEX SILVER CITY');
insert into statuses (status) values ('Position Closed for review for different position');
insert into statuses (status) values ('No Contact ');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('Endorsed to NNIT');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to NNIT');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Already in UHG Database');
insert into statuses (status) values ('Endorsed to TP Baguio');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Endorsed');
insert into statuses (status) values ('Encoded to taleo');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Encoded to taleo');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Encoded to taleo');
insert into statuses (status) values ('Encoded to taleo');
insert into statuses (status) values ('Endorsed');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to CSS Corp.');
insert into statuses (status) values ('For Paperscreening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Endorsed to CSS Corp.');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to CSS Corp.');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('Endorsed to TP-Edsa');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Poor Reception / For CB');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Aura');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Failed PreScreening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Valid Philippine Number');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('For Validation NNIT');
insert into statuses (status) values ('Not Available');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Endorsed to Cebu IT Park');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Already Applied to TP');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('Endorsed to IBEX SILVER CITY');
insert into statuses (status) values ('Failed ');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('Invalid Number');
insert into statuses (status) values ('Invalid ');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Ringing No Answer');
insert into statuses (status) values ('Already processed by other Head hunter');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Unavailable');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('No Contact');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Unattended');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Valid Philippine No');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Accenture Validation- POS Support Engineer');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Lacks Qualification');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Endorsed to CSS Corp.');
insert into statuses (status) values ('Failed');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer / SMS sent');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Amenable to Work in Ilocos');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For CB- Not From Ilocos');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For Pooling');
insert into statuses (status) values ('For CB- For Workstation Manager');
insert into statuses (status) values ('No Valid Phil. No.');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For CB- Workstation Engineer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('For Paper Screening');
insert into statuses (status) values ('Endorsed to Amikat');
insert into statuses (status) values ('Endorsed to Comodo');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Endorsed to TP Davao');
insert into statuses (status) values ('Endorsed to Amikat');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to Sitel Baguio');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Cebu Insular');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Already Employed');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Invalid with existing record in UHG');
insert into statuses (status) values ('Encoded to taleo');
insert into statuses (status) values ('Not Qualified/ No IT Experience');
insert into statuses (status) values ('Valid to Accenture ');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Invited to F2F Interview and coaching / TP EDSA');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer SMS Sent');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to IBEX SILVER CITY');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Failed');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');

insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('Valid for Accenture');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Valid for Accenture');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Endorsed to IBEX Tiendesitas');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to AMIKAT');
insert into statuses (status) values ('Endorsed to TP Davao');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsement to TP Cebu Insular');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Endorsed to IBEX Silver City');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Already failed TP and SITEL Baguio');
insert into statuses (status) values ('For CB 2:40 PM');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Endorsed to EXL Alabang');
insert into statuses (status) values ('No Valid Philippine No.');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Not Interested');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Baguio');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('Endorsed to TP Cebu Insular');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('For pooling already applied to TP');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Edsa');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Endorsed to TP Cebu Insular');
insert into statuses (status) values ('No Answer ');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('CNR / Sms Sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Applied to TP Last week');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('Low signal reception / Sms Sent');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Endorsed to IBEX Silver City');
insert into statuses (status) values ('For Callback');
insert into statuses (status) values ('Already applied to IBEX and TP');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Fairview');
insert into statuses (status) values ('Endorsed to IBEX Paranaque');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to Cebu IT Park');
insert into statuses (status) values ('For CB');
insert into statuses (status) values ('Encoded to Taleo');
insert into statuses (status) values ('Not Qualified');

insert into statuses (status) values ('No Answer / Sms Sent');
insert into statuses (status) values ('Endorsed to IBEX Silver City');
insert into statuses (status) values ('Endorsed to TP Davao');
insert into statuses (status) values ('Endorsed to TP Davao');
insert into statuses (status) values ('Endorsed to TP Ayala');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Cebu Insular');
insert into statuses (status) values ('Already applied to TP');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('No Answer / Sms Sent');
insert into statuses (status) values ('Already applied to TP');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('CNR');
insert into statuses (status) values ('Failed CHRS Screening');
insert into statuses (status) values ('Failed for Accenture - only amenable in Metro Manila');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Valid Philippine ID');
insert into statuses (status) values ('For Pooling');
insert into statuses (status) values ('Not Qualified');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer / Sms Sent');
insert into statuses (status) values ('Endorsed to TP Cebu Insular');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Currently Employed with Accenture');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('For Clearing');
insert into statuses (status) values ('Endorsed to TP Edsa');
insert into statuses (status) values ('Endorsed to CSS Corp');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('CNR / SMS Sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('No Answer / SMS Sent');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Already applied to TP');
insert into statuses (status) values ('Endorsed to TP Cebu IT Park');
insert into statuses (status) values ('Already applied to TP');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Profiled for IGT/Amikat');
insert into statuses (status) values ('Medical Issue/Sick');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('CNR / SMS Sent');
insert into statuses (status) values ('Failed Screening');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Comodo');
insert into statuses (status) values ('for Validation');

insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('for f2f Interview');
insert into statuses (status) values ('for f2f Interview');
insert into statuses (status) values ('for f2f Interview');
insert into statuses (status) values ('for f2f Interview');
insert into statuses (status) values ('for f2f Interview');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to TP');
insert into statuses (status) values ('Endorsed to TP');
insert into statuses (status) values ('Endorsed to TP');
insert into statuses (status) values ('Endorsed to TP');
insert into statuses (status) values ('Endorsed to TP');
insert into statuses (status) values ('Endorsed to TP');
insert into statuses (status) values ('Endorsed to TP');
insert into statuses (status) values ('for f2f Interview');
insert into statuses (status) values ('for f2f Interview');
insert into statuses (status) values ('for f2f Interview');
insert into statuses (status) values ('for f2f Interview');
insert into statuses (status) values ('for f2f Interview 1-11-2016');
insert into statuses (status) values ('for f2f Interview 1-11-2016');
insert into statuses (status) values ('for f2f Interview 1-11-2016');
insert into statuses (status) values ('for f2f Interview 1-11-2016');
insert into statuses (status) values ('for f2f Interview 1-11-2016');
insert into statuses (status) values ('For f2f interview');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('For f2f interview');
insert into statuses (status) values ('For f2f interview');
insert into statuses (status) values ('For f2f interview');
insert into statuses (status) values ('Endorsed to WNS');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paper Screening');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paper Screening');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('For Paper Screening');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to HGS');
insert into statuses (status) values ('For Paper Screening');
insert into statuses (status) values ('For Paper Screening');
insert into statuses (status) values ('For PAper Screening');
insert into statuses (status) values ('For PAper Screening');
insert into statuses (status) values ('For PAper Screening');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to PC');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('For Validation');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('f2f interview ');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to TP');
insert into statuses (status) values ('Endorse to GPC for f2f interview');
insert into statuses (status) values ('Endorsed to YSA ');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to GPC');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('No Answer');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Endorsed to Accenture Bilingual Hiring Event');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('For pooling');
insert into statuses (status) values ('Endorsed to Accenture');
insert into statuses (status) values ('Call back at 12nn 20-Jan-2016');
insert into statuses (status) values ('Endorsed to Accenture Bilingual Hiring Event');
insert into statuses (status) values ('Endorsed to Accenture Bilingual Hiring Event');
insert into statuses (status) values ('Endorsed to Accenture Bilingual Hiring Event');
insert into statuses (status) values ('For CGI Validation');
insert into statuses (status) values ('Endorsed to Accenture Bilingual Hiring Event');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('Callback/Busy/Ringing Only');
insert into statuses (status) values ('for Accenture Validation');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('For f2f interview 1/25/2016');
insert into statuses (status) values ('Callback/Busy/Ringing Only');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('not qualified');
insert into statuses (status) values ('Invalid for Accenture');
insert into statuses (status) values ('For f2f interview 1/25/2016');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
insert into statuses (status) values ('Endorsed to YSA');
