insert into sources (source) values('PostingJob');
insert into sources (source) values('Avaya Voice Network');
insert into sources (source) values('BestJobs');
insert into sources (source) values('CebuJobs');
insert into sources (source) values('Central Mailbox');
insert into sources (source) values('ConnectTalentnow');
insert into sources (source) values('Endorsed');
insert into sources (source) values('Facebook');
insert into sources (source) values('Job Posting');
insert into sources (source) values('From Bilingual email');
insert into sources (source) values('GigaJobs');
insert into sources (source) values('GMail');
insert into sources (source) values('Greatjobs');
insert into sources (source) values('Indeed');
insert into sources (source) values('Jobs Cloud');
insert into sources (source) values('Jobvertise');
insert into sources (source) values('LinkedIn');
insert into sources (source) values('MBClassified');
insert into sources (source) values('PinoyJobs');
insert into sources (source) values('Post Job Free');
insert into sources (source) values('Referral');
insert into sources (source) values('Textblast ');
insert into sources (source) values('Trovit.Ph');
insert into sources (source) values('Others');
