\c chrs_employees
begin;
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201000001','Rheyan','Feliciano','Lipardo','Owner & Managing Director','waynelipardo.chrs@gmail.com','wayne.lipardo@gmail.com ');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400066','Judy Ann','Lantican','Reginaldo','Asst Client and Recruitment Manager','jreginaldo.chrs@gmail.com','N/A');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400072','Ken','Villanueva','Tapdasan','HR and Admin Associate','ktapdasan.chrs@gmail.com','bluraven20@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400078','Lita','Llanera','Elejido','Talent Acquisition Associate','lelejido.chrs@gmail.com','lhitaelejido@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400081','Vincent','Yturralde','Ramil','Asst Client & Recruitment Supervisor','vramil.chrs@gmail.com','N/A');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400087','Faya Lou','Mahinay','Parenas','Asst Recruitment & Client Specialist','fparenas.chrs@gmail.com','N/A');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400084','Michelle','Balasta','Gongura','HR Associate','mgongura.chrs@gmail.com','N/A');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400088','Arjev','Price','De Los Reyes','Asst HR Manager','adlreyes.chrs@gmail.com','arjevdelosreyes@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400059','Marilyn May','Villano','Bolocon','Talent Acquisition Associate','mbolocon.chrs@gmail.com','bolocon.marilynmay@yahoo.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201300004','Mary Grace','Soriano ','Lacerna','Client & Recruitment Supervisor','gracesoriano.chrs@gmail.com','N/A');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400089','Ma. Fe','Pariscal','Bolinas','Business Development Associate','mfbolinas.chrs@gmail.com','mafe.bolinas@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400097','Ariel','Dela Cruz','Solis','Accounting Consultant','N/A','acsolis10@yahoo.com ');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400098','Rolando','Garfin','Lipardo','Liason Associate','N/A','N/A');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400100','Rolando','Carillo','Fabi','Accounting Supervisor','rolly.fabi@chrsglobal.com','rollyfabi_23@yahoo.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400102','John Erasmus Mari','Regado','Fernandez','HR Associate','N/A','johnerasmusmarif@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400058','Rodette Joyce','Magaway','Laurio','HR Associate','jlaurio.chrs@gmail.com','N/A');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400103','Gerlie','Pagaduan','Andres','HR Associate','gerlie.andres@chrsglobal.com','gerlieandres0201@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400104','Eliza','Alcaraz','Mandique','Corporate Quality Supervisor','eliza.mandique@chrsglobal.com','eliza.mandique@yahoo.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400105','Rafael','Aurelio','Pascual','Project IT Manager','rafael.pascual@chrsglobal.com','rpascual0812@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400106','Eralyn May','Bayot','Adino','HR Associate Intern','emadino.chrs@gmail.com','jinra25@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400107','Ana Margarita','Hernandez','Galero','HR Associate Intern','amgalero.chrs@gmail.com','anamgalero@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400108','Irone John','Mendoza','Amor','HR Associate Intern','ijamor.chrs@gmail.com','ironejohn@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400109','Angelica','Barredo','Abaleta','HR Associate Intern','aabelata.chrs@gmail.com','a.abaleta@yahoo.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400110','Shena Mae','Jardinel','Nava','HR Associate Intern','shena.nava@chrsglobal.com','shenamaenavacalma@yahoo.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400111','Angelyn','Daguro','Cuevas','HR Associate Intern','acuevas.chrs@gmail.com','angelyn.cuevas1017@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400112','Alween Orange','Ceredon','Gemao','HR Associate Intern','aogemao.chrs@gmail.com','orangegemao@yahoo.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400113','Aprilil Mae','Denalo','Nefulda','HR Associate Intern','Aprilil.nefulda@chrsglobal.com','Aprililmaenefulda@ymail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400114','Karen','Medo','Esmeralda','Cashier/Skin Care Advisor','kesmeraldo@gmail.com','kesmeraldo.chrs@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400115','Jennifer','Araneta','Balucay','Cashier/Skin Care Advisor','jbalucay.chrs@gmail.com','jennbalucay93@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400117','Arlene','Diama','Obasa','Cashier/Skin Care Advisor','aobasa.chrs@gmail.com','obasa_arlene@yahoo.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400118','Cristina','Tulayan','Ibanez','HR Associate Intern','cibanez.chrs@gmail.com','tina_041481@yahoo.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400119','Alyssa','Iligan','Panaguiton','HR Associate Intern','apanaguiton.chrs@gmail.com','panaguitonalyssaend121@gmail.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400120','Aimee','Gaborni','Legaspi','HR Associate Intern','alegaspi.chrs@gmail.com','aimeelgsp@icloud.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400121','Kathleen Kay','Macalino','Ongcal','Clinic Consultant','kkongcal.chrs@gmail.com','kathleen.ongcal@chrsglobal.com');
insert into employees(employee_id, first_name, middle_name, last_name,position,email_address,business_email_address) values('201400122','Marry Jeane','Genteroy','Sadsad','Clinic Consultant','mjsadsad.chrs@gmail.com','marry.sadsad@chrsglobal.com');

update employees set level = 'C-Level' where employee_id = '201000001';
update employees set level = 'Manager' where employee_id = '201400066';
update employees set level = 'Associate' where employee_id = '201400072';
update employees set level = 'Associate' where employee_id = '201400078';
update employees set level = 'Supervisor' where employee_id = '201400081';
update employees set level = 'Specialist' where employee_id = '201400087';
update employees set level = 'Intern' where employee_id = '201400084';
update employees set level = 'Asst Manager' where employee_id = '201400088';
update employees set level = 'Associate' where employee_id = '201400059';
update employees set level = 'Supervisor' where employee_id = '201300004';
update employees set level = 'Associate' where employee_id = '201400089';
update employees set level = 'Associate' where employee_id = '201400097';
update employees set level = 'Associate' where employee_id = '201400098';
update employees set level = 'Supervisor' where employee_id = '201400100';
update employees set level = 'Associate' where employee_id = '201400102';
update employees set level = 'Associate' where employee_id = '201400058';
update employees set level = 'Intern' where employee_id = '201400103';
update employees set level = 'Supervisor' where employee_id = '201400104';
update employees set level = 'Manager' where employee_id = '201400105';
update employees set level = 'Associate' where employee_id = '201400106';
update employees set level = 'Associate' where employee_id = '201400107';
update employees set level = 'Associate' where employee_id = '201400108';
update employees set level = 'Associate' where employee_id = '201400109';
update employees set level = 'Associate' where employee_id = '201400110';
update employees set level = 'Associate' where employee_id = '201400111';
update employees set level = 'Associate' where employee_id = '201400112';
update employees set level = 'Associate' where employee_id = '201400113';
update employees set level = 'Associate' where employee_id = '201400114';
update employees set level = 'Associate' where employee_id = '201400115';
update employees set level = 'Associate' where employee_id = '201400117';
update employees set level = 'Associate' where employee_id = '201400118';
update employees set level = 'Associate' where employee_id = '201400119';
update employees set level = 'Associate' where employee_id = '201400120';
update employees set level = 'Associate' where employee_id = '201400121';
update employees set level = 'Associate' where employee_id = '201400122';
commit;