insert into job_positions (position) values ('CSR - Marketing and Sales');
insert into job_positions (position) values ('CSR - Media');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Banking Fraud');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Non Voice');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR - Office Supplies');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('IT Internal Support');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR-Telco');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR-Banking Fraud');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR- Banking Fraud');
insert into job_positions (position) values ('CSR/TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Sales Training Officer');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR- MEdia & Publishing');
insert into job_positions (position) values ('FSR/Specialist');
insert into job_positions (position) values ('CSR- MEdia & Publishing');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('TSR- Gaming');
insert into job_positions (position) values ('CSR- MEdia & Publishing');
insert into job_positions (position) values ('TSR for Gaming');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Bank Compliance Officer');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Telco');
insert into job_positions (position) values ('CSR Telco');
insert into job_positions (position) values ('CSR-Consumer Voice ');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Business Writing');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR media & publishing');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Healthcare Associates ');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR- Telco');

insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR-Cable');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR-non voice');
insert into job_positions (position) values ('CSR-Healthcare');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR Cable & Internet');

insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR Sales Agent');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR Sales Agent');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel-Airline');
insert into job_positions (position) values ('CSR Travel Account');
insert into job_positions (position) values ('CSR Non Voice');
insert into job_positions (position) values ('CSR Non Voice');
insert into job_positions (position) values ('CSR-Consumer Services');
insert into job_positions (position) values ('CSR for Travel Account');
insert into job_positions (position) values ('Dayshift CSR - telecom');
insert into job_positions (position) values ('CSR -Banking Retail');
insert into job_positions (position) values ('CSR-Travel airline');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR for Sales');
insert into job_positions (position) values ('CSR for marketing & Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Dayshift CSR - telecom');
insert into job_positions (position) values ('CSR-Healthcare');
insert into job_positions (position) values ('CSR Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Travel Airline');
insert into job_positions (position) values ('TSR for Cable, Int. & Phone');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('TSR Cable');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR- Pioneer Non Voice');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('Recruitment phone inter.');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR Pioneer Non Voice');
insert into job_positions (position) values ('CSR Pioneer Non Voice');
insert into job_positions (position) values ('Mobilization Analyst');
insert into job_positions (position) values ('CSR- Consumer Services');
insert into job_positions (position) values ('CSR- Pioneer Non Voice');
insert into job_positions (position) values ('CSR- Pioneer Non Voice');
insert into job_positions (position) values ('No position attached');
insert into job_positions (position) values ('CSR- Pioneer Non Voice');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR- Pioneer Non Voice');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR- Pioneer Non Voice');
insert into job_positions (position) values ('local account');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Banking fraud');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Dayshift CSR - telecom');
insert into job_positions (position) values ('CSR- Pioneer Non Voice');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR Banking fraud');
insert into job_positions (position) values ('CSR Travel-Airline');
insert into job_positions (position) values ('Dayshift CSR - telecom');
insert into job_positions (position) values ('Dayshift CSR - telecom');
insert into job_positions (position) values ('CSR-Banking');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Dayshift CSR - telecom');
insert into job_positions (position) values ('CSR- Pioneer Non Voice');
insert into job_positions (position) values ('CSR-Banking');
insert into job_positions (position) values ('CSR-Travel airline');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Mandarin CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Javascript Developer');
insert into job_positions (position) values ('CSR Office Supplies');
insert into job_positions (position) values ('CSR Gaming Console');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Japanese Language Specialist');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Bahasa Indo CSR');
insert into job_positions (position) values ('CSR-Banking retail');

insert into job_positions (position) values ('CSR-Pioneer Non Voice');
insert into job_positions (position) values ('CSR-Pioneer Non Voice');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Java Developer');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Banking Retail');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR -Banking Retail');
insert into job_positions (position) values ('CSR-Travel Airline');
insert into job_positions (position) values ('CSR for Sales');
insert into job_positions (position) values ('Finance and Enterprise Mgr');
insert into job_positions (position) values ('Facilities Ops Manager');
insert into job_positions (position) values ('Purchasing Manager');
insert into job_positions (position) values ('People Program Associate Mgr.');
insert into job_positions (position) values ('Risk and Compliance Mgr.');
insert into job_positions (position) values ('Treasury and Billing Manager');
insert into job_positions (position) values ('Analytics Manager');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('TSR - Cable Company');
insert into job_positions (position) values ('CSR Non Voice');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR - Banking Retail');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR - Operating System');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR for Sales');
insert into job_positions (position) values ('CSR-Banking Retail');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('TSR for Pioneer Account');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR for Ordertaking, telco & travel account');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('CSR - Travel Airline');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('CSR -Gaming Console');
insert into job_positions (position) values ('CSR -Gaming Console');
insert into job_positions (position) values ('CSR-Banking Fraud');
insert into job_positions (position) values ('CSR Pioneer Non Voice');
insert into job_positions (position) values ('CSR-Banking');
insert into job_positions (position) values ('CSR-Email Support');
insert into job_positions (position) values ('CSR/TSR Pioneer Gaming');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('CSR-Telco');
insert into job_positions (position) values ('USRN - EXL');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('Care Mgt Global Process Owner');
insert into job_positions (position) values ('Project Manager');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('Marketing Specialist');
insert into job_positions (position) values ('Care Mgt Global Process Owner');
insert into job_positions (position) values ('Project Manager');
insert into job_positions (position) values ('Project Manager');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Pioneer Non Voice');
insert into job_positions (position) values ('CSR-Pioneer Non Voice');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Pioneer Non Voice');
insert into job_positions (position) values ('CSR-Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Gaming Account');
insert into job_positions (position) values ('CSR-Banking Retail');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Pioneer Non Voice');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Travel Airline');
insert into job_positions (position) values ('CSR-Pioneer Non Voice');
insert into job_positions (position) values ('CSR-Telecom');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Banking');
insert into job_positions (position) values ('CSR-Banking');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Travel Account');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Treasury and Billing Manager');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR - BAnking');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('CSR - Travel Airline');
insert into job_positions (position) values ('Care Mgt Global Process Owner');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('TSR for Printers');
insert into job_positions (position) values ('CSR-Cable Company');
insert into job_positions (position) values ('TSR for Cable, Internet & Phone');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Banking Pilot Class (Wave 1)');
insert into job_positions (position) values ('CSR-Banking Pilot Class (Wave 1)');
insert into job_positions (position) values ('CSR-Travel Airline');
insert into job_positions (position) values ('CSR-Banking Pilot Class (Wave 1)');
insert into job_positions (position) values ('CSR-Banking Pilot Class (Wave 1)');
insert into job_positions (position) values ('CSR for Travel Account');
insert into job_positions (position) values ('CSR for travel, hotel & entertainment');
insert into job_positions (position) values ('CSR for travel, hotel & entertainment');
insert into job_positions (position) values ('Care Mgt Global Process Owner');
insert into job_positions (position) values ('CSR for travel, hotel & entertainment');
insert into job_positions (position) values ('CSR-Banking Fraud');
insert into job_positions (position) values ('CSR for travel airline');
insert into job_positions (position) values ('CSR for travel, hotel & entertainment');
insert into job_positions (position) values ('CSR-Banking Pilot Class (Wave 1)');
insert into job_positions (position) values ('CSR-Banking Pilot Class (Wave 1)');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR for travel, hotel & entertainment');
insert into job_positions (position) values ('CSR for Travel - Airline');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR-Banking Pilot Class (Wave 1)');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR Non voice for pioneer account');
insert into job_positions (position) values ('CSR for travel, hotel & entertainment');
insert into job_positions (position) values ('CSR Gaming Account');
insert into job_positions (position) values ('CSR for pilot class (wave 1)');
insert into job_positions (position) values ('CSR Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Travel');
insert into job_positions (position) values ('CSR for Travel Account');
insert into job_positions (position) values ('CSR Travel ');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for Sales');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Healthcare Specialist CSR non voice');
insert into job_positions (position) values ('CSR for Australian Retail');
insert into job_positions (position) values ('CSR-Consumer Services (Email)');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for pilot class (wave 1)');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('CSR Australian Retail');
insert into job_positions (position) values ('Sales Training Officer');
insert into job_positions (position) values ('CSR for Travel Airline');
insert into job_positions (position) values ('CSR for Travel');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('Care Mgt Global Process Owner');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Care Mgt Global Process Owner');
insert into job_positions (position) values ('Finance and Enterprise Mgr');
insert into job_positions (position) values ('CSR Travel, Hotel & Entertainment');
insert into job_positions (position) values ('CSR Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Travel Account');
insert into job_positions (position) values ('Facilities Ops Manager');
insert into job_positions (position) values ('CSR for Travel, Hotel & Entertainment');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Finance and Enterprise Performance Mgr');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('CSR for pilot class (wave 1)');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('CSR for pilot class (wave 1)');
insert into job_positions (position) values ('CSR for Consumer Services ( Email)');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('CSR for Travel, Hotel & Entertainment');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('CSR Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Travel, Hotel & Entertainment');
insert into job_positions (position) values ('CSR for Travel -Airline');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('Finance and Enterprise Performance Mgr');
insert into job_positions (position) values ('CSR for Consumer Services ( Email)');
insert into job_positions (position) values ('CSR - gaming account');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR - Cable Company');
insert into job_positions (position) values ('STO');
insert into job_positions (position) values ('Business Development Manager');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('CSR for pilot class (wave 1)');
insert into job_positions (position) values ('CSR for Travel Account');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('Customer service Representative for Sales');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('Customer service Representative');
insert into job_positions (position) values ('CSR for pilot class (wave 1)');
insert into job_positions (position) values ('CSR - Billing & Sales');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR Pilot Class ( Wave 1)');
insert into job_positions (position) values ('CSR Pilot Class ( Wave 1)');
insert into job_positions (position) values ('CSR for Travel airline');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for Travel, Hotel & Entertainment');
insert into job_positions (position) values ('Customer Service Representative for Travel');
insert into job_positions (position) values ('CSR for Pioneer Healthcare');
insert into job_positions (position) values ('Dayshift CSR Telecom');
insert into job_positions (position) values ('CSR for Pioneer Healthcare');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('CSR for pilot class (wave 1)');
insert into job_positions (position) values ('CSR for pilot class (wave 1)');
insert into job_positions (position) values ('CSR for Travel, Hotel & Entertainment');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Travel Airline');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('CSR - Pioneer Non Voice');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR - Pioneer Non Voice');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for Travel, Hotel & Entertainment');
insert into job_positions (position) values ('CSR - Pioneer Non Voice');
insert into job_positions (position) values ('CSR for Travel, Hotel & Entertainment');
insert into job_positions (position) values ('CSR Healtcare');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Consumer Services (Email)');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for Travel, Hotel & Entertainment');
insert into job_positions (position) values ('Customer service Representative for Sales');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Marketing Associate');

insert into job_positions (position) values ('Customer Service Representative - Sales');
insert into job_positions (position) values ('Dayshift CSR');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('Customer Service Representative-Banking');
insert into job_positions (position) values ('CSR-Travel Airline');
insert into job_positions (position) values ('CSR-Consumer Services (Email)');
insert into job_positions (position) values ('Customer Service Representative-Banking');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('Branch Operations Supervisor');
insert into job_positions (position) values ('PH RN Medical Coder');
insert into job_positions (position) values ('Care Management Global Process Owner');
insert into job_positions (position) values ('CSR - Banking Fraud');
insert into job_positions (position) values ('CSR- Pilot class (Wave 1)');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Pilot Class (Wave 1)');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative -travel airline');
insert into job_positions (position) values ('CSR-Banking Retail');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Dayshift CSR - Telecom');
insert into job_positions (position) values ('Customer Sales Agent');
insert into job_positions (position) values ('CSR - Travel account');
insert into job_positions (position) values ('Customer Service Representative ');
insert into job_positions (position) values ('Care Management Global Process Owner');
insert into job_positions (position) values ('Facilities Operations Manager');
insert into job_positions (position) values ('CSR-Banking Retail');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('CSR- Pilot class (Wave 1)');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative - Banking');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR Travel, Hotel & Restaurant');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative - Banking');
insert into job_positions (position) values ('CSR for a Pioneer Healthcare Account');
insert into job_positions (position) values ('Field Sales Specialists');
insert into job_positions (position) values ('USRN - Accenture');
insert into job_positions (position) values ('Care Management Global Process Owner');
insert into job_positions (position) values ('PH RN Medical Coder');
insert into job_positions (position) values ('USRN - EXL');
insert into job_positions (position) values ('Sales Training Officer');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('HR BPO Manager');
insert into job_positions (position) values ('Marketing Specialist');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('PH RN Medical Coder');
insert into job_positions (position) values ('PH RN Medical Coder');
insert into job_positions (position) values ('Facilities Operations Manager');
insert into job_positions (position) values ('ACN Ops HR People Advisor Manager');
insert into job_positions (position) values ('Care Management Global Process Owner');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('IBEX');
insert into job_positions (position) values ('PH RN Medical Coder');
insert into job_positions (position) values ('Senior Project Manager');
insert into job_positions (position) values ('JAPANESE CSR FOR SALES');
insert into job_positions (position) values ('Graphic Designer');
insert into job_positions (position) values ('Senior Project Manager');
insert into job_positions (position) values ('AVP - Human Resource');
insert into job_positions (position) values ('IT Project Manager');
insert into job_positions (position) values ('Design Senior Analyst - Art Director');
insert into job_positions (position) values ('Unit Manager');
insert into job_positions (position) values ('Branch Operations Supervisor');
insert into job_positions (position) values ('AVP - Human Resource');
insert into job_positions (position) values ('Workforce Management Lead');
insert into job_positions (position) values ('AVP - Human Resource');
insert into job_positions (position) values ('AVP - Human Resource');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR-Travel Account');
insert into job_positions (position) values ('CSR-Travel');
insert into job_positions (position) values ('Customer Service Representative');
insert into job_positions (position) values ('CSR- Travel Airline');
insert into job_positions (position) values ('AVP - Human Resource');
insert into job_positions (position) values ('Corporate Sales Represenatives');
insert into job_positions (position) values ('Design Senior Analyst - Art Director');
insert into job_positions (position) values ('Design Senior Analyst - Art Director');
insert into job_positions (position) values ('Nurse Practitioner Representatives');
insert into job_positions (position) values ('Nurse Practitioner Representatives');
insert into job_positions (position) values ('Japanese CSR - Sales');
insert into job_positions (position) values ('Customer Service Representatives');
insert into job_positions (position) values ('CSR - Consumer Services');
insert into job_positions (position) values ('Customer Service Representatives');
insert into job_positions (position) values ('Customer Service Representatives');
insert into job_positions (position) values ('Corporate Sales Represenatives');
insert into job_positions (position) values ('Design Senior Analyst - Art Director');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Business Development Manager');
insert into job_positions (position) values ('AVP - Human Resource');
insert into job_positions (position) values ('Unit Manager');
insert into job_positions (position) values ('AVP - Human Resources');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('AVP - Human Resources');
insert into job_positions (position) values ('AVP - Human Resources');
insert into job_positions (position) values ('AVP - Human Resources');
insert into job_positions (position) values ('Sales Training Officer');
insert into job_positions (position) values ('MS EXCHANGE Server Administration');
insert into job_positions (position) values ('Mobilization Sr. Analyst');
insert into job_positions (position) values ('Inventory Manager');
insert into job_positions (position) values ('AVP - Human Resources');
insert into job_positions (position) values ('Senior Project Manager');
insert into job_positions (position) values ('Technical Trainer');
insert into job_positions (position) values ('Mandarin CSR');
insert into job_positions (position) values ('Mandarin CSR');
insert into job_positions (position) values ('AVP - Human Resources');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Design Senior Analyst - Art Director');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Accountant (Non CPA)');
insert into job_positions (position) values ('Arabic Analyst');
insert into job_positions (position) values (' IT TECHNICAL TEAM LEAD');
insert into job_positions (position) values ('MS OFFICE 365 Support Engineer');
insert into job_positions (position) values ('Graphic Designer');
insert into job_positions (position) values ('SAP Business Planning and Consolidation');
insert into job_positions (position) values ('SAP Basis');
insert into job_positions (position) values ('Graphic Designer');
insert into job_positions (position) values (' DevOps');
insert into job_positions (position) values ('SAP Basis Specialist');
insert into job_positions (position) values ('Mobilization Team Lead');
insert into job_positions (position) values ('Spanish Analyst');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Spanish Analyst');
insert into job_positions (position) values ('TSR - IT Helpdesk');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Sales Training Officer');
insert into job_positions (position) values ('HR Talent Strategy Manager');
insert into job_positions (position) values ('Sales Training Officer');
insert into job_positions (position) values ('Nurse Practitioner Representatives');
insert into job_positions (position) values ('Senior Java Developer');
insert into job_positions (position) values ('AVP - Human Resources');
insert into job_positions (position) values ('ACN Ops HR People Advisor Manager');
insert into job_positions (position) values ('System Implementation Analytics');
insert into job_positions (position) values ('DevOps Engineer');
insert into job_positions (position) values ('Brand Manager');
insert into job_positions (position) values ('Business Development Manager');
insert into job_positions (position) values ('Purchasing Manager');
insert into job_positions (position) values ('Pharmacy Unit Manager');
insert into job_positions (position) values ('ACN Ops HR People Advisor Manager');
insert into job_positions (position) values ('Project Manager');
insert into job_positions (position) values ('ACN Ops HR People Advisor Manager');
insert into job_positions (position) values ('SAP BASIS Specialist');
insert into job_positions (position) values ('Senior.NET DEVELOPER');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('Senior.NET DEVELOPER');
insert into job_positions (position) values ('Senior.NET DEVELOPER');
insert into job_positions (position) values ('MS OFFICE 365 Support Engineer');
insert into job_positions (position) values (' MS EXCHANGE Server Administrator');
insert into job_positions (position) values ('Senior.NET DEVELOPER');
insert into job_positions (position) values ('Senior.NET DEVELOPER');
insert into job_positions (position) values ('Project Manager / Business Dev't Mgr');
insert into job_positions (position) values ('HR Talent Strategy Manager');
insert into job_positions (position) values ('Nurse Practitioner Representatives');
insert into job_positions (position) values ('AVP - Human Resources');
insert into job_positions (position) values ('AVP - Human Resources');
insert into job_positions (position) values ('Design Senior Analyst - Art Director');
insert into job_positions (position) values ('Treasury and Billing Manager');
insert into job_positions (position) values ('Social Media Representatives');
insert into job_positions (position) values ('Credit and Collection Specialist');
insert into job_positions (position) values ('Credit and Collection Specialist');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Accountant (Non CPA)');

insert into job_positions (position) values (' MS OFFICE SUPPORT ENGINEER');
insert into job_positions (position) values ('Senior.NET DEVELOPER');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel Airline');
insert into job_positions (position) values ('Accounting Position');
insert into job_positions (position) values ('CSR for Travel, Hotel and Entertainment');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Banking Retail');
insert into job_positions (position) values ('CSR Travel Airline');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Healthcare');
insert into job_positions (position) values ('CSR Office Supplies');
insert into job_positions (position) values ('CSR Office Supplies');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Travel');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR - Healthcare');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR Banking Retail');
insert into job_positions (position) values ('CSR Banking Retail');
insert into job_positions (position) values ('CSR Banking Retail');
insert into job_positions (position) values ('CSR Banking Retail');
insert into job_positions (position) values ('CSR - Travel');
insert into job_positions (position) values ('CSR for Pioneer Non Voice');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR- IT Helpdesk');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Healthcare');
insert into job_positions (position) values ('CSR - Healthcare');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Healthcare');
insert into job_positions (position) values ('CSR - Banking Retail');
insert into job_positions (position) values ('CSR - Healthcare');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Email Support Representatives');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Ph RN ');
insert into job_positions (position) values ('Brand Manager');
insert into job_positions (position) values ('Nurse Practitioner');
insert into job_positions (position) values ('Nurse Practitioner');
insert into job_positions (position) values ('SAP Basis Specialist');
insert into job_positions (position) values ('SAP Basis Specialist');
insert into job_positions (position) values ('AX Functional Consultant/SAP Basis Specialist');
insert into job_positions (position) values ('MS Sharepoint Administrator');
insert into job_positions (position) values ('Japanese CSR ');
insert into job_positions (position) values ('German Language ');
insert into job_positions (position) values ('Corporate Training Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('IBEX');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('SENIOR .NET DEVELOPER');
insert into job_positions (position) values ('Senior .Net Developer');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Banking Retail');
insert into job_positions (position) values ('IT OPERATIONS MANAGER');
insert into job_positions (position) values ('Dev Ops Engineer');
insert into job_positions (position) values ('Senior.NET DEVELOPER');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('Dev Ops Engineer');
insert into job_positions (position) values ('Operations Manager');
insert into job_positions (position) values ('Operations Manager');
insert into job_positions (position) values ('CBDM ');
insert into job_positions (position) values ('Business Dev't Manager');
insert into job_positions (position) values ('Business Dev't Manager');
insert into job_positions (position) values ('Product Dev't Manager');
insert into job_positions (position) values ('Nurse Practitioner');
insert into job_positions (position) values ('Corporate Training Manager');
insert into job_positions (position) values ('Purchasing Manager');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('USRN Clinical Analyst');
insert into job_positions (position) values ('Supply Chain and Procurement Mgr');
insert into job_positions (position) values ('System Implementation- Delivery');
insert into job_positions (position) values (' IT SYSTEM MANAGEMENT ANALYST');

insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Travel, Hotel and Entertainment');
insert into job_positions (position) values ('CSR - Travel, Hotel and Entertainment');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Japanese Speaking CSR ');
insert into job_positions (position) values ('CSR - Travel, Hotel and Entertainment');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('German Language ');
insert into job_positions (position) values ('Cantonese Speaking CSR');
insert into job_positions (position) values ('Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('CSR for Travel');
insert into job_positions (position) values ('CSR for Banking');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Nurse Practitioner Representative');
insert into job_positions (position) values ('Business Development Managers');
insert into job_positions (position) values ('Supply Chain and Procurement Manager');
insert into job_positions (position) values ('Supply Chain and Procurement Manager');
insert into job_positions (position) values ('USRN Clinical Analyst');
insert into job_positions (position) values ('Internal Audit Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR For Travel Airline');
insert into job_positions (position) values ('CSR For Travel Airline');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Korean Speaking ');
insert into job_positions (position) values ('CSR');

insert into job_positions (position) values ('Design Senior Analyst');
insert into job_positions (position) values ('HR Talent Strategy Manager');
insert into job_positions (position) values ('Corporate Communication Senior Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Sales Representative');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel, Hotel And Entertainment');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Travel, Hotel and Entertainment');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Medical Representative');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Healthcare');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Travel Airline');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Accenture-Mandarin');
insert into job_positions (position) values ('MS-SQL Server Integration Services');
insert into job_positions (position) values ('System Implementation Project Manager');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('AX Functional Consultant');
insert into job_positions (position) values ('M3 ERP Business Consultant');
insert into job_positions (position) values ('Functional Consultant');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR DAYSHIFT');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('EDI LEAD');
insert into job_positions (position) values ('Workstation Engineer');
insert into job_positions (position) values ('CSR - Travel, Hotel and Entertainment ');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Banking Retail');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Healthcare');
insert into job_positions (position) values ('CSR Healthcare');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Banking Retail');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR for Banking Retail');
insert into job_positions (position) values ('CSR - Travel');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Banking Retail');
insert into job_positions (position) values ('CSR for Healthcare');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR - Banking Retail');
insert into job_positions (position) values ('Email Support Representative');
insert into job_positions (position) values ('CSR for Banking Loans');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Nurse Practitioner Representatives');
insert into job_positions (position) values ('Design Senior Analyst');
insert into job_positions (position) values ('Retail Unit Head');
insert into job_positions (position) values ('Procurement Manager');
insert into job_positions (position) values ('Mechanical Engineer');
insert into job_positions (position) values ('Mechanical Engineer');
insert into job_positions (position) values ('Nurse Practitioner Representatives');
insert into job_positions (position) values ('Sales training Officer');
insert into job_positions (position) values ('Project Managers');
insert into job_positions (position) values ('Design Senior Analyst - Video');
insert into job_positions (position) values ('CSR Travel, Hotel And Entertainment');
insert into job_positions (position) values ('CSR - Travel Airline');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel Airlines');
insert into job_positions (position) values ('CSR Travel, Hotel And Entertainment');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel, Hotel And Entertainment');
insert into job_positions (position) values ('CSR Travel Airlines');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Banking');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel, Hotel And Entertainment');
insert into job_positions (position) values ('CSR Travel, Hotel And Entertainment');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Nurse Practitioner Representatives');
insert into job_positions (position) values ('Sales training Officer');
insert into job_positions (position) values ('Nurse Practitioner Representatives');
insert into job_positions (position) values ('Nurse Practitioner Representatives');
insert into job_positions (position) values ('Business Development Managers');
insert into job_positions (position) values ('Workstation Engineer (Ilocos)');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('German Language ');
insert into job_positions (position) values ('Thai. Language ');
insert into job_positions (position) values ('CSR For Hotel Reservations');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR for Cable TV and Internet');
insert into job_positions (position) values ('CSR/TSR');
insert into job_positions (position) values ('Customer Sales Agent (Utilities)');
insert into job_positions (position) values ('CSR for Travel Airline');
insert into job_positions (position) values ('CSR Travel, Hotel And Entertainment');
insert into job_positions (position) values ('WORKSTATION ENGINEER');
insert into job_positions (position) values ('Collections Specialist');


insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Not in the Phil.');

insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Sales Training Officer');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('CSR for Cable TV and Internet');
insert into job_positions (position) values ('CSR Travel Airline');
insert into job_positions (position) values ('Email Support Representative');
insert into job_positions (position) values ('CSR Travel Airline');
insert into job_positions (position) values ('CSR Financial');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel, Hotel and Entertainment');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Associate Software Engineer');
insert into job_positions (position) values ('Associate Software Engineer');
insert into job_positions (position) values ('CSR for Banking claims');
insert into job_positions (position) values ('Associate Software Engineer');
insert into job_positions (position) values ('CSR Financial Account');
insert into job_positions (position) values ('Associate Software Engineer');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR/TSR');
insert into job_positions (position) values ('Technical Trainer');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('WORKSTATION ENGINEER');
insert into job_positions (position) values ('CSR Financial Account');
insert into job_positions (position) values ('WORKSTATION ENGINEER');
insert into job_positions (position) values ('WORKSTATION ENGINEER');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Solution Architect');
insert into job_positions (position) values ('Associate Software Engineer');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Hotel Reservations');
insert into job_positions (position) values ('CSR Hotel Reservations and Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel Airline');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('CSR For Healthcare');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('IT System Management Analyst');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Sr Voice/Data Network Analyst');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('CSR/TSR');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('CSR - Travel Airline');
insert into job_positions (position) values ('Voice/Data Network Analyst');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Operations Excellent Associate Managers');
insert into job_positions (position) values ('Accounting Officer');
insert into job_positions (position) values ('RN');
insert into job_positions (position) values ('Care Management Global Process Owner');
insert into job_positions (position) values ('PHRN');
insert into job_positions (position) values ('Design Senior Analyst');
insert into job_positions (position) values ('Design Senior Analyst');
insert into job_positions (position) values ('Supply Chain and Procurement Manager');
insert into job_positions (position) values ('PHRN');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Data Sales Account Executive');
insert into job_positions (position) values ('Business Development Manager');
insert into job_positions (position) values ('SAP BPC Professional');
insert into job_positions (position) values ('Japanese Speaker');
insert into job_positions (position) values ('Business Development Manager');
insert into job_positions (position) values ('Design Senior Analyst');
insert into job_positions (position) values ('Japanese Speaker');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('Japanese Speaker');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSA');
insert into job_positions (position) values ('CSR for Hotel Reservations');
insert into job_positions (position) values ('CSR-Healthcare');
insert into job_positions (position) values ('CSR - Telecom');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Telecom');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('CSR Financial');
insert into job_positions (position) values ('Salesforce.com Software Development');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Report Analyst');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Corporate Communication Senior Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Travel Hotel Sales');
insert into job_positions (position) values ('CSR for Travel Hotel Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Nurse Practitioner');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR For Travel E. Services');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('IT System Management Analyst');
insert into job_positions (position) values ('Oracle Hyperion Consultant');
insert into job_positions (position) values ('IT System Management Analyst');
insert into job_positions (position) values ('SAP Basis Specialist');
insert into job_positions (position) values ('IT System Management Analyst');
insert into job_positions (position) values ('Workstation Engineer');
insert into job_positions (position) values ('IT System Management Analyst');
insert into job_positions (position) values ('Intelligent Network Engineer');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('IT Client Engagement Manager');
insert into job_positions (position) values ('Workstation Engineer');
insert into job_positions (position) values ('IT System Management Analyst');
insert into job_positions (position) values ('Associate Software Engr.');
insert into job_positions (position) values ('Associate Software Engr.');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Japanese CSR');
insert into job_positions (position) values ('Workstation Engineer');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Japanese CSR ');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Banking Retail');
insert into job_positions (position) values ('Software Engineer');
insert into job_positions (position) values ('Workstation Engineer');
insert into job_positions (position) values ('Senior IT Project Manager');
insert into job_positions (position) values ('Workstation Engineer');
insert into job_positions (position) values ('Front-End Web Developer');
insert into job_positions (position) values ('Front-End Web Developer');
insert into job_positions (position) values ('Associate Software Engineer');
insert into job_positions (position) values ('Intelligent Network Engineer');
insert into job_positions (position) values ('Intelligent Network Engineer');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('Workstation Engineer');
insert into job_positions (position) values ('CSR for Travel Hotel Sales');
insert into job_positions (position) values ('Project Manager');
insert into job_positions (position) values ('CSR For Airlines');
insert into job_positions (position) values ('Social Media Expert');
insert into job_positions (position) values ('CSR for Travel Hotel Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR For Hotel Reservations');
insert into job_positions (position) values ('(Dayshift) CSR - Telecom');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Banking');
insert into job_positions (position) values ('CSR Financial');
insert into job_positions (position) values ('CSR Travel Hotel Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Financial');
insert into job_positions (position) values ('CSR for Travel Hotel Sales');
insert into job_positions (position) values ('Sales Representative');
insert into job_positions (position) values ('CSR - Pioneer Non Voice');
insert into job_positions (position) values ('CSR - Travel E. Services');
insert into job_positions (position) values ('Nurse Practitioner');
insert into job_positions (position) values ('Nurse Practitioner');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('Mandarin Language');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('IT System Management Analyst');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Mangento Developer');
insert into job_positions (position) values ('CSR - Banking Retail');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('MS SQL Server Analysis');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('IT Security Management Analyst');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('General Manager');
insert into job_positions (position) values ('Design Senior Analyst (Art Director)');
insert into job_positions (position) values ('Nurse Practitioner');
insert into job_positions (position) values ('Thai Language');
insert into job_positions (position) values ('Merchandising Manager');
insert into job_positions (position) values ('Mandarin Language');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel Hotel Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Banking');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Travel Hotel Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR for Financial Services');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Banking');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR For Financial');
insert into job_positions (position) values ('CSR For Banking');
insert into job_positions (position) values ('CSR Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Technology Architect');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Liferay Portal Developer');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('IT Security Management Analyst');
insert into job_positions (position) values ('Associate Software Engineer');
insert into job_positions (position) values ('Associate Software Engineer');
insert into job_positions (position) values ('CSR Travel Airline');
insert into job_positions (position) values ('CSR - Financial');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Travel Hotel Sales');
insert into job_positions (position) values ('CSR - Travel and Hospitality');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Area Sales Manager');
insert into job_positions (position) values ('TSR');
insert into job_positions (position) values ('CSR - Healthcare account');
insert into job_positions (position) values ('USR Case Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Premiere Financial');
insert into job_positions (position) values ('CSR - Travel and Hospitality');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Travel Hotel Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Design Senior Analyst-Video');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Area Sales Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Accenture');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Corporate Communication  Manager');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR For Banking Retail');
insert into job_positions (position) values ('Application Developer.Net');
insert into job_positions (position) values ('Associate IT Security Analyst');
insert into job_positions (position) values ('Associate Software Engineer');

insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Banking Retail');
insert into job_positions (position) values ('CSR - Travel Hotel Sales');
insert into job_positions (position) values ('TSR - Cable, Internet and Phone');
insert into job_positions (position) values ('CSR - Hotel Reservations');
insert into job_positions (position) values ('CSR Travel Hotel Sales');
insert into job_positions (position) values ('CSR - Travel and Hospitality');
insert into job_positions (position) values ('CSR - Travel, Hotel and Entertainment');
insert into job_positions (position) values ('Magento Developer');
insert into job_positions (position) values ('CSR - Banking Claims');
insert into job_positions (position) values ('Workstation Engineer');
insert into job_positions (position) values ('Technology Architect');
insert into job_positions (position) values ('SAP BPC Professional');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('Sr. Recruitment Manager');
insert into job_positions (position) values ('IT Operations Manager');
insert into job_positions (position) values ('CSR - Premiere Financial');
insert into job_positions (position) values ('CSR - Travel Hotel Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('MS-SQL Server Integration Services');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR Travel Hotel Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR/TSR');
insert into job_positions (position) values ('TSR ');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Financial');
insert into job_positions (position) values ('CSR Travel Hotel Sales');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR -  Travel and Hospitality');
insert into job_positions (position) values ('CSR - Travel E. Services');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR - Travel and Hospitality');
insert into job_positions (position) values ('TSR - Cable, Internet and Phone');
insert into job_positions (position) values ('Sales Agent');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('Design Senior Analyst');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('CSR');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Vietnamese Analyst');
insert into job_positions (position) values ('Bahasa Indo Analyst');
insert into job_positions (position) values ('Vietnamese Analyst');
insert into job_positions (position) values ('Bahasa Indo Analyst');
insert into job_positions (position) values ('Mandarin Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('German Language');
insert into job_positions (position) values ('Korean Language');
insert into job_positions (position) values ('Social Media Expert');
insert into job_positions (position) values ('Procurement Manager');
insert into job_positions (position) values ('Team Leader');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Vietnamese Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Vietnamese Language');
insert into job_positions (position) values ('Vietnamese Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Vietnamese Language');
insert into job_positions (position) values ('Thai Language');
insert into job_positions (position) values ('Thai Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('USRN Clinical Analyst');
insert into job_positions (position) values ('Facilities Manager');
insert into job_positions (position) values ('Design Senior Analyst');
insert into job_positions (position) values ('Operation Manager');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Vietnamese Language');
insert into job_positions (position) values ('Vietnamese Language');
insert into job_positions (position) values ('Vietnamese Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Bahasa Indo Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Mandarin Language');
insert into job_positions (position) values ('Mandarin Language');
insert into job_positions (position) values ('Bahasa Malay Language');
insert into job_positions (position) values ('Cantonese Language');
insert into job_positions (position) values ('RN/Skin Care Advisor ');
insert into job_positions (position) values ('RN/Skin Care Advisor ');
insert into job_positions (position) values ('RN/Skin Care Advisor ');
insert into job_positions (position) values ('Vietnamese Language');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('RN/Skin Care Advisor ');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Delivery Rider');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Team Leader');
insert into job_positions (position) values ('PHRN');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('PHRN');
insert into job_positions (position) values ('Cluster Business Development Manager');
insert into job_positions (position) values ('Senior Human Resource Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Area Sales Manager');
insert into job_positions (position) values ('Area Sales Manager');
insert into job_positions (position) values ('Marketing Manager');
insert into job_positions (position) values ('USRN');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Trade Marketing Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Brand Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Supply Chain Manager');
insert into job_positions (position) values ('Vietnamese CSR');
insert into job_positions (position) values ('Vietnamese CSR');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Skin Care Advisor ');
insert into job_positions (position) values ('Driver');
insert into job_positions (position) values ('Driver');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Receiptionist/Cashier ');
insert into job_positions (position) values ('Skin Care Advisor ');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('Skin Care Advisor ');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Office Staff');
insert into job_positions (position) values ('Driver ');
insert into job_positions (position) values ('Receiptionist/Cashier ');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Receiptionist/Cashier ');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Spanish Language');
insert into job_positions (position) values ('Bahasa Indo Language');
insert into job_positions (position) values ('Vietnamese Language');
insert into job_positions (position) values ('Accounting Officer');
insert into job_positions (position) values ('Skin Care Advisor ');
insert into job_positions (position) values ('Skin Care Advisor ');
insert into job_positions (position) values ('Accounting Officer');
insert into job_positions (position) values ('Cashier');
insert into job_positions (position) values ('IT Quality Consultant');
insert into job_positions (position) values ('POS Support');
insert into job_positions (position) values ('Japanese Language');
insert into job_positions (position) values ('Skin Care Advisor ');
insert into job_positions (position) values ('IT Openings');
insert into job_positions (position) values ('Registrar Associate');
insert into job_positions (position) values ('Network Architect');
insert into job_positions (position) values ('Spanish Analyst');
insert into job_positions (position) values ('Spanish Analyst');
insert into job_positions (position) values ('Japanese Analyst');
insert into job_positions (position) values ('AX Developer');
insert into job_positions (position) values ('Spanish Analyst');
insert into job_positions (position) values ('POS Support');
insert into job_positions (position) values ('Technical Support Engineer');
insert into job_positions (position) values ('Cisco Routing and Switching');
insert into job_positions (position) values ('POS Support');
insert into job_positions (position) values ('Network Architect');
insert into job_positions (position) values ('Delivery Rider');
insert into job_positions (position) values ('Technical Support Representative');
insert into job_positions (position) values ('Network Architect');
insert into job_positions (position) values ('Network Architect');
insert into job_positions (position) values ('Cisco Routing and Switching');
insert into job_positions (position) values ('SI Project Manager');
insert into job_positions (position) values ('POS Support');
insert into job_positions (position) values ('SAP');
insert into job_positions (position) values ('Network Engineer');
insert into job_positions (position) values ('Cisco Routing and Switching');
insert into job_positions (position) values ('Accounting Officer');
insert into job_positions (position) values ('Sales Distributor Specialist');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Trade Marketing Manager');
insert into job_positions (position) values ('Trade Marketing Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Regional Sales Manager');
insert into job_positions (position) values ('Trade Marketing Manager');
insert into job_positions (position) values ('Network Architecture');
