begin;
update employees set department = '{20}' where first_name = 'Rheyan' and last_name = 'Lipardo';
update employees set department = '{27}' where first_name = 'Eralyn May' and last_name = 'Adino';
update employees set department = '{27}' where first_name = 'Irone John' and last_name = 'Amor';
update employees set department = '{24}' where first_name = 'Gerlie' and last_name = 'Andres';
update employees set department = '{29}' where first_name = 'Jennifer' and last_name = 'Balucay';
update employees set department = '{21}' where first_name = 'Marilyn May' and last_name = 'Bolocon';
update employees set department = '{21}' where first_name = 'Angelyn' and last_name = 'Cuevas';
update employees set department = '{24}' where first_name = 'Arjev' and last_name = 'De Los Reyes';
update employees set department = '{28}' where first_name = 'Lita' and last_name = 'Elejido';
update employees set department = '{29}' where first_name = 'Karen' and last_name = 'Esmeralda';
update employees set department = '{23}' where first_name = 'Rolando' and last_name = 'Fabi';
update employees set department = '{27}' where first_name = 'Ana Margarita' and last_name = 'Galero';
update employees set department = '{21}' where first_name = 'Alween Orange' and last_name = 'Gemao';
update employees set department = '{21}' where first_name = 'Michelle' and last_name = 'Gongura';
update employees set department = '{22,29}' where first_name = 'Cristina' and last_name = 'Ibanez';
update employees set department = '{22,29}' where first_name = 'Mary Grace' and last_name = 'Lacerna';
update employees set department = '{28}' where first_name = 'Rodette Joyce' and last_name = 'Laurio';
update employees set department = '{22,29}' where first_name = 'Aimee' and last_name = 'Legaspi';
update employees set department = '{23}' where first_name = 'Rolando' and last_name = 'Lipardo';
update employees set department = '{25}' where first_name = 'Eliza' and last_name = 'Mandique';
update employees set department = '{21}' where first_name = 'Shena Mae' and last_name = 'Nava';
update employees set department = '{28}' where first_name = 'April Mae' and last_name = 'Nefulda';
update employees set department = '{29}' where first_name = 'Arlene' and last_name = 'Obasa';
update employees set department = '{29}' where first_name = 'Kathleen Kay' and last_name = 'Ongcal';
update employees set department = '{24}' where first_name = 'Alyssa' and last_name = 'Panaguiton';
update employees set department = '{27}' where first_name = 'Faya Lou' and last_name = 'Parenas';
update employees set department = '{26}' where first_name = 'Rafael' and last_name = 'Pascual';
update employees set department = '{21}' where first_name = 'Vincent' and last_name = 'Ramil';
update employees set department = '{28}' where first_name = 'Judy Ann' and last_name = 'Reginaldo';
update employees set department = '{29}' where first_name = 'Marry Jeane' and last_name = 'Sadsad';
update employees set department = '{23}' where first_name = 'Ariel' and last_name = 'Solis';
update employees set department = '{27}' where first_name = 'Ken' and last_name = 'Tapdasan';
commit;